# Archivo de configuración para los parámetros del robot SMILEi
smilei_state_machine:
  ros__parameters:
    use_sim_time: false
    
    # Límites de las articulaciones (en radianes)
    joint_limits:
      q_l1: [-1.5708, 1.5708]  # [-90°, 90°]
      q_l2: [-1.5708, 0.7854]  # [-90°, 45°]
      q_l3: [-1.5708, 2.3562]  # [-90°, 135°]
      q_l4: [-1.5708, 1.5708]  # [-90°, 90°]
      q_r1: [-1.5708, 1.5708]  # [-90°, 90°]
      q_r2: [-0.7854, 1.5708]  # [-45°, 90°]
      q_r3: [-2.3562, 1.5708]  # [-135°, 90°]
      q_r4: [-1.5708, 1.5708]  # [-90°, 90°]


    # Parámetros físicos del brazo derecho
    right_arm:
      # Masas (kg)
      m1: 0.361
      m2: 0.400
      m3: 0.452
      m4: 0.181
      
      # Longitudes de eslabones (m)
      d2: 0.113
      a3: 0.123
      
      # Parámetros de inercia
      rcx1: -0.0371
      rcx2: -0.0154
      rcy2: 0.0812
      rcz2: -0.2084
      rcy3: 0.1585
      rcz3: 0.1687
      rcx4: -0.1282
      rcy4: -0.0039
      rcz4: -0.4192
      
      # Gravedad
      g: 9.81

    # Parámetros físicos del brazo izquierdo
    left_arm:
      # Masas (kg)
      m1: 0.361
      m2: 0.400
      m3: 0.452
      m4: 0.181
      
      # Longitudes de eslabones (m)
      d2: 0.113
      a3: 0.123
      
      # Parámetros de inercia
      rcx1: -0.0264
      rcx2: -0.0235
      rcy2: -0.0609
      rcz2: -0.0386
      rcy3: 0.0150
      rcz3: 0.0022
      rcx4: -0.0228
      rcy4: 0.0568
      rcz4: -0.0279
      
      # Gravedad
      g: 9.81

# Configuración global para todos los nodos del proceso
/**:
  ros__parameters:
    robot_name: 'operador'  # Nombre del robot
    
    # Configuración para teleoperación remota
    remote_teleoperation:
      # Configuración de red
      is_machine_a: true              # true para máquina A, false para máquina B
      machine_a_ip: '192.168.0.100'   # IP de la máquina A
      machine_b_ip: '192.168.0.2'   # IP de la máquina B
      
      # Configuración de motores
      motor_ids: [1,2,3]                  # Lista de IDs de motores a controlar
      
      # Ganancias de control PD para teleoperación (valores fijos del behavior)
      control_gains:
        kp: 0.2  # Ganancia proporcional fija
        kd: 0.01   # Ganancia derivativa fija
        kt: 0.35  # Constante de torque fija
      
      # Config0uración de comunicación
      socket_timeout: 0.001
      max_communication_errors: 10
      control_frequency: 10000